# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'npm'
      - name: Display variables
        run: |
          echo "Hello action started!"
          echo "github.event_name: ${{ github.event_name }}!"
          echo "github.ref: ${{ github.ref }}!"
      - run: npm ci
      - run: npm run validate
      - run: npm test
      - run: npm run test:e2e
      - run: npm run build
      - run: npm run build-storybook
      - if: (github.event_name == 'push') && github.ref == 'refs/heads/main'
        name: Deploy production
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          target: 'test-project-github-actions'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_PROJECT_GITHUB_ACTIONS }}'
          channelId: live
          projectId: test-project-github-actions
      - if: (github.event_name == 'push') && github.ref == 'refs/heads/main'
        name: Deploy production storybook
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          target: 'sb-epicgames-iamkarthick'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_PROJECT_GITHUB_ACTIONS }}'
          channelId: live-sb
          projectId: test-project-github-actions
      - if: (github.event_name == 'push') && github.ref == 'refs/heads/develop'
        name: Deploy development
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          target: 'epicgames-dev-iamkarthick'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_PROJECT_GITHUB_ACTIONS }}'
          channelId: dev
          projectId: test-project-github-actions
      - if: (github.event_name == 'push') && github.ref == 'refs/heads/develop'
        name: Deploy development storybook
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          target: 'sb-epicgames-dev-iamkarthick'
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_PROJECT_GITHUB_ACTIONS }}'
          channelId: dev-sb
          projectId: test-project-github-actions
