# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'npm'
      - name: Display variables
        run: |
          echo "Hello action started!"
          echo "github.event_name: ${{ github.event_name }}!"
          echo "github.ref: ${{ github.ref }}!"
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"
      - run: npm ci
      - if: (github.event_name == 'push' || github.event_name == 'pull_request') && github.ref == 'refs/heads/main'
        name: Conditional branch for main
        run: echo 'This is main branch'
      - if: (github.event_name == 'push' || github.event_name == 'pull_request') && github.ref == 'refs/heads/develop'
        name: Conditional branch for develop
        run: echo 'This is develop branch'
      - run: npm run validate
      - run: npm test
      - run: npm run test:e2e
      - run: npm run build --if-present
